### PR TITLE
Add shresth12-jain-sort-colors-cplusplus.cpp

### PR DESCRIPTION
**Pull request by shresth12-jain**
Added Solution to problem 75 Sort Colors in C++. Kindly let me know if any modification required.

### CODE REVIEW

**Comment by miikkasaxlund** [comment]
Running your code on LeetCode gave the following output: 
checksolution

Check the solution again and let me know when it is working, I will then merge the request

**Comment by miikkasaxlund** [comment]
It seems to be working, merging the pull request now. Thanks for the contribution!

**Comment by shresth12-jain** [comment]
Thank you so much for letting me know my mistake & also for merging it.

**Comment by miikkasaxlund** [comment]
You are welcome, my friend!

**Pull request merged**
